#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5F1B2A0789F12B11 (jeremie.galarneau@gmail.com)
#
Name     : compat-babeltrace-one
Version  : 1.5.7
Release  : 8
URL      : http://www.efficios.com/files/babeltrace/babeltrace-1.5.7.tar.bz2
Source0  : http://www.efficios.com/files/babeltrace/babeltrace-1.5.7.tar.bz2
Source1  : http://www.efficios.com/files/babeltrace/babeltrace-1.5.7.tar.bz2.asc
Summary  : libbabeltrace-ctf provides the specific bits necessary to read a Common Trace Format (CTF) trace.
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: compat-babeltrace-one-bin = %{version}-%{release}
Requires: compat-babeltrace-one-lib = %{version}-%{release}
Requires: compat-babeltrace-one-license = %{version}-%{release}
Requires: compat-babeltrace-one-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : elfutils-dev
BuildRequires : flex
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(uuid)
BuildRequires : popt-dev
BuildRequires : util-linux-dev

%description
BabelTrace - Trace Format Babel Tower
This project provides trace read and write libraries, as well as a trace
converter. A plugin can be created for any trace format to allow its conversion
to/from another trace format.

%package bin
Summary: bin components for the compat-babeltrace-one package.
Group: Binaries
Requires: compat-babeltrace-one-license = %{version}-%{release}

%description bin
bin components for the compat-babeltrace-one package.


%package dev
Summary: dev components for the compat-babeltrace-one package.
Group: Development
Requires: compat-babeltrace-one-lib = %{version}-%{release}
Requires: compat-babeltrace-one-bin = %{version}-%{release}
Provides: compat-babeltrace-one-devel = %{version}-%{release}
Requires: compat-babeltrace-one = %{version}-%{release}

%description dev
dev components for the compat-babeltrace-one package.


%package doc
Summary: doc components for the compat-babeltrace-one package.
Group: Documentation
Requires: compat-babeltrace-one-man = %{version}-%{release}

%description doc
doc components for the compat-babeltrace-one package.


%package lib
Summary: lib components for the compat-babeltrace-one package.
Group: Libraries
Requires: compat-babeltrace-one-license = %{version}-%{release}

%description lib
lib components for the compat-babeltrace-one package.


%package license
Summary: license components for the compat-babeltrace-one package.
Group: Default

%description license
license components for the compat-babeltrace-one package.


%package man
Summary: man components for the compat-babeltrace-one package.
Group: Default

%description man
man components for the compat-babeltrace-one package.


%prep
%setup -q -n babeltrace-1.5.7
cd %{_builddir}/babeltrace-1.5.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672167167
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1672167167
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-babeltrace-one
cp %{_builddir}/babeltrace-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/compat-babeltrace-one/769beafb15b6f735182c448baaceff57eca32ed6
cp %{_builddir}/babeltrace-%{version}/mit-license.txt %{buildroot}/usr/share/package-licenses/compat-babeltrace-one/896db08d9336fddb884ddd3994bd28993200ea1a
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/babeltrace
/usr/bin/babeltrace-log

%files dev
%defattr(-,root,root,-)
/usr/include/babeltrace/babeltrace.h
/usr/include/babeltrace/clock-types.h
/usr/include/babeltrace/context.h
/usr/include/babeltrace/ctf-ir/clock.h
/usr/include/babeltrace/ctf-ir/event-class.h
/usr/include/babeltrace/ctf-ir/event.h
/usr/include/babeltrace/ctf-ir/field-types.h
/usr/include/babeltrace/ctf-ir/fields.h
/usr/include/babeltrace/ctf-ir/stream-class.h
/usr/include/babeltrace/ctf-ir/utils.h
/usr/include/babeltrace/ctf-writer/clock.h
/usr/include/babeltrace/ctf-writer/event-fields.h
/usr/include/babeltrace/ctf-writer/event-types.h
/usr/include/babeltrace/ctf-writer/event.h
/usr/include/babeltrace/ctf-writer/stream-class.h
/usr/include/babeltrace/ctf-writer/stream.h
/usr/include/babeltrace/ctf-writer/writer.h
/usr/include/babeltrace/ctf/callbacks.h
/usr/include/babeltrace/ctf/events.h
/usr/include/babeltrace/ctf/iterator.h
/usr/include/babeltrace/error.h
/usr/include/babeltrace/format.h
/usr/include/babeltrace/iterator.h
/usr/include/babeltrace/list.h
/usr/include/babeltrace/trace-handle.h
/usr/lib64/libbabeltrace-ctf-metadata.so
/usr/lib64/libbabeltrace-ctf-text.so
/usr/lib64/libbabeltrace-ctf.so
/usr/lib64/libbabeltrace-dummy.so
/usr/lib64/libbabeltrace-lttng-live.so
/usr/lib64/libbabeltrace.so
/usr/lib64/pkgconfig/babeltrace-ctf.pc
/usr/lib64/pkgconfig/babeltrace.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/babeltrace/API.txt
/usr/share/doc/babeltrace/ChangeLog
/usr/share/doc/babeltrace/LICENSE
/usr/share/doc/babeltrace/gpl-2.0.txt
/usr/share/doc/babeltrace/lttng-live.txt
/usr/share/doc/babeltrace/mit-license.txt
/usr/share/doc/babeltrace/std-ext-lib.txt

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbabeltrace-ctf-metadata.so.1
/usr/lib64/libbabeltrace-ctf-metadata.so.1.0.0
/usr/lib64/libbabeltrace-ctf-text.so.1
/usr/lib64/libbabeltrace-ctf-text.so.1.0.0
/usr/lib64/libbabeltrace-ctf.so.1
/usr/lib64/libbabeltrace-ctf.so.1.0.0
/usr/lib64/libbabeltrace-dummy.so.1
/usr/lib64/libbabeltrace-dummy.so.1.0.0
/usr/lib64/libbabeltrace-lttng-live.so.1
/usr/lib64/libbabeltrace-lttng-live.so.1.0.0
/usr/lib64/libbabeltrace.so.1
/usr/lib64/libbabeltrace.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-babeltrace-one/769beafb15b6f735182c448baaceff57eca32ed6
/usr/share/package-licenses/compat-babeltrace-one/896db08d9336fddb884ddd3994bd28993200ea1a

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/babeltrace-log.1
/usr/share/man/man1/babeltrace.1
